[2023-11-21T04:44:36.142+0000] {taskinstance.py:1149} INFO - Dependencies not met for <TaskInstance: wisdomise_database_semi_final.get_start_date scheduled__2023-11-21T00:57:37.003903+00:00 [failed]>, dependency 'Task Instance State' FAILED: Task is in the 'failed' state.
[2023-11-21T04:44:36.154+0000] {local_task_job_runner.py:154} INFO - Task is not able to be run
