[2023-11-16T11:51:04.909+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Backend_run.run_docker_compose_task scheduled__2023-01-08T00:00:00+00:00 [queued]>
[2023-11-16T11:51:05.090+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Backend_run.run_docker_compose_task scheduled__2023-01-08T00:00:00+00:00 [queued]>
[2023-11-16T11:51:05.092+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2023-11-16T11:51:05.452+0000] {taskinstance.py:1382} INFO - Executing <Task(BashOperator): run_docker_compose_task> on 2023-01-08 00:00:00+00:00
[2023-11-16T11:51:05.504+0000] {standard_task_runner.py:57} INFO - Started process 146 to run task
[2023-11-16T11:51:06.012+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'Backend_run', 'run_docker_compose_task', 'scheduled__2023-01-08T00:00:00+00:00', '--job-id', '12', '--raw', '--subdir', 'DAGS_FOLDER/dags.py', '--cfg-path', '/tmp/tmpy_nxj__w']
[2023-11-16T11:51:06.063+0000] {standard_task_runner.py:85} INFO - Job 12: Subtask run_docker_compose_task
[2023-11-16T11:51:07.417+0000] {task_command.py:416} INFO - Running <TaskInstance: Backend_run.run_docker_compose_task scheduled__2023-01-08T00:00:00+00:00 [running]> on host b631f0e58258
[2023-11-16T11:51:10.520+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='your_name' AIRFLOW_CTX_DAG_ID='Backend_run' AIRFLOW_CTX_TASK_ID='run_docker_compose_task' AIRFLOW_CTX_EXECUTION_DATE='2023-01-08T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-01-08T00:00:00+00:00'
[2023-11-16T11:51:10.558+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2023-11-16T11:51:10.602+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'docker-compose -f ./../personal_webapp/docker-compose.yml up -d']
[2023-11-16T11:51:10.725+0000] {subprocess.py:86} INFO - Output:
[2023-11-16T11:51:10.751+0000] {subprocess.py:93} INFO - /bin/bash: line 1: docker-compose: command not found
[2023-11-16T11:51:10.751+0000] {subprocess.py:97} INFO - Command exited with return code 127
[2023-11-16T11:51:10.780+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 210, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 127.
[2023-11-16T11:51:10.795+0000] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=Backend_run, task_id=run_docker_compose_task, execution_date=20230108T000000, start_date=20231116T115104, end_date=20231116T115110
[2023-11-16T11:51:10.848+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 12 for task run_docker_compose_task (Bash command failed. The command returned a non-zero exit code 127.; 146)
[2023-11-16T11:51:11.175+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-11-16T11:51:11.238+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
